name: Compile JOSS paper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile paper
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss

      - name: Upload compiled paper
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper.pdf

